services:
  - type: web
    name: nexus-stock
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        generateValue: false
